---
- name: Create journald config directory
  become: True
  file:
    path: "{{ journald_config_path | dirname }}"
    mode: 0755
    owner: root
    group: root
    recurse: True
  notify: Restart systemd-journald

- name: Create journald configuration
  become: True
  template:
    src: journald.conf.j2
    dest: "{{ journald_config_path }}"
    mode: 0644
    owner: root
    group: root
  notify: Restart systemd-journald

- name: Wipe persistent journal directory
  become: True
  file:
    path: /var/log/journal
    state: absent
  when: journald_wipe_persistent
